// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3L63mv7LJntyQnytW1cqI753bT2YiF2w',
    appId: '1:246971442416:android:c008ef02d16caac6e6ce35',
    messagingSenderId: '246971442416',
    projectId: 'canteen-management-8c75e',
    storageBucket: 'canteen-management-8c75e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBINhGhAlv7J3TIiA7Bptd2SVT3b97ZlcY',
    appId: '1:246971442416:ios:8f7b3590b8ac0d0be6ce35',
    messagingSenderId: '246971442416',
    projectId: 'canteen-management-8c75e',
    storageBucket: 'canteen-management-8c75e.appspot.com',
    androidClientId: '246971442416-6ua11b98d5jbejc4p26mpgsqsaagfhm0.apps.googleusercontent.com',
    iosClientId: '246971442416-d3iu4rm12t4tt9a5k2k2cjkh9ckk2p9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.canteenAppDaiict',
  );
}
